### ISSUE TITLE
Add retina support

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-sys#11]
Via `highdpi` in Window settings

**Comment by dawidgorny** [comment]
I added `highdpi` support. Tested in a browser with and without fullscreen mode. https://github.com/pex-gl/pex-sys/pull/12

**Comment by vorg** [comment]
Implemented in https://github.com/pex-gl/pex-sys/commit/5c75c604a50643f9d444d7852021d31d5ec98da1
