### ISSUE TITLE
Fullscreen confusion in Browser

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-sys#13]
Currently we use `fullScreen` in the browser window when we mean `fullWindow`

So in a way writing this

```
settings: {
        width:  1280,
        height: 720,
        fullscreen: isBrowser ? true : false
},
```

Could be replaced with:

```
settings: {
        width: isBrowser ? window.innerWidth : 1280,
        height: isBrowser ? window.innerHeight : 720
}
```

Downsides:
- you would need to apply `margin:0` and `overflow:hidden` to `document.body.style` manually (this was automagically done in WindowBrowser before)
- ?

Or

```
settings: {
        width: Screen.getWidth(),
        height: Screen.getHeight()
}
```

But then again you get big window on desktop which is probably not what you need

**Comment by automat** [comment]
I agree, this is confusing. 

Did `fullscreen:true` work in previous `pex-sys` for plask setup, did it create a true fullscreen window or just full span (didnt test the correct plask.setFullscreen() from 694206a)?
Because thats the only downside i see when going with the 2nd option, (im ok with removing auto style injection on `body`). You would loose the convenient fullscreen setup for plask. Otherwise you would have to go with:
```
    setup: function(){
        if(isPlask()){
            this.setFullScreen(true);
            //handle resize
        }
    }
```
What about `fullSpan` (or something else that doesnt collide with fullscreen) as an alternative for windows taking all available space? Then you could keep writing this:

```
    settings: {
        width:  1280,
        height: 720,
        fullSpan: isBrowser ? true : false
    }
```

**Comment by vorg** [comment]
So i tested the built-in `setFullscreen` function from Plask and all it does is removing the title bar. So you would need to move it to 0,0 manually. But then there is still no way to resize the window programmatically in Plask :/ I've asked Dean why is that (you might need to recreate OpenGL surfaces or something).

`fullSpan` is interesting but then what would `fullScreen` do in the browser?

Would rather try to avoid that: 
```
settings: {
   fullScreen: isBrowser ? false : true,
   fullSpan: isBrowser ? true : false
}
```

Trying to figure out how to resize Plask window. That would be ideal.. We could then remove fullScreen parameter from settings and switch to fullscreen at runtime on any platform.

**Comment by automat** [comment]
Yeah, i guess `fullScreen` would switch the browser window to fullScreen mode immediately on load, guess thats somewhat evil from browser users perspective, but might also be something desirable within installations context, eg quick-setup (although of course, you could just trigger it via shortcut or menu) or default fullScreen in `electron` app without setting options for `browser-window` or triggering its `maximize`, or in `nwjs`. On the other hand this is always just one `setFullScreen(true)` away in `setup()` (plus optional user conformation).

So yes, removing it from settings and being able to switch to proper fullscreen at runtime in plask would be a good solution.

**Comment by vorg** [comment]
In Three.js if you pass canvas the renderer keeps it's size, otherwise it will create fullscreen Canvas
